In [1]:
#question 1

#Ordinal encoding and label encoding are both techniques used in machine learning to convert categorical data into numerical format, but they are used in different scenarios.

from sklearn.preprocessing import LabelEncoder

data = ['red', 'green', 'blue', 'red', 'green']
label_encoder = LabelEncoder()
encoded_data = label_encoder.fit_transform(data)
print(encoded_data)


[2 1 0 2 1]


In [3]:
#question 2

#Target Guided Ordinal Encoding is a technique used in machine learning to encode categorical variables based on the target variable. This method is particularly useful when dealing with ordinal categorical variables. The idea is to assign numerical values to the categories based on the likelihood or mean of the target variable for each category. This way, the encoding captures the relationship between the categorical variable and the target variable.

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


# Create a sample dataset
data = {'Education': ['High School', 'Bachelor', 'Master', 'High School', 'PhD', 'Bachelor']}
target = {'Target': [0, 1, 1, 0, 1, 0]}
df = pd.DataFrame(data)
df['Target'] = pd.DataFrame(target)

# Split the dataset into features and target
X = df.drop('Target', axis=1)
y = df['Target']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply Target Guided Ordinal Encoding to 'Education'
encoder = OrdinalEncoder(encoding_method='ordered', variables=['Education'])
X_train_encoded = encoder.fit_transform(X_train, y_train)
X_test_encoded = encoder.transform(X_test)

# Train a model (Random Forest, for example)
model = RandomForestClassifier(random_state=42)
model.fit(X_train_encoded, y_train)

# Make predictions and evaluate the model
y_pred = model.predict(X_test_encoded)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')


NameError: name 'OrdinalEncoder' is not defined

In [ ]:
#question 3

#Covariance is a statistical measure that describes how much two random variables change together. In other words, it quantifies the degree to which the values of two variables tend to move in relation to each other. If the covariance is positive, it indicates that higher values of one variable are associated with higher values of the other, and vice versa. If the covariance is negative, it means that higher values of one variable are associated with lower values of the other.

In [4]:
#question 4

from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Create a sample dataset
data = {'Color': ['red', 'green', 'blue', 'red', 'green'],
        'Size': ['small', 'medium', 'large', 'medium', 'small'],
        'Material': ['wood', 'metal', 'plastic', 'metal', 'wood']}
df = pd.DataFrame(data)

# Initialize label encoders for each categorical variable
label_encoder_color = LabelEncoder()
label_encoder_size = LabelEncoder()
label_encoder_material = LabelEncoder()

# Apply label encoding to each categorical variable
df['Color_encoded'] = label_encoder_color.fit_transform(df['Color'])
df['Size_encoded'] = label_encoder_size.fit_transform(df['Size'])
df['Material_encoded'] = label_encoder_material.fit_transform(df['Material'])

# Display the encoded DataFrame
print(df)


   Color    Size Material  Color_encoded  Size_encoded  Material_encoded
0    red   small     wood              2             2                 2
1  green  medium    metal              1             1                 0
2   blue   large  plastic              0             0                 1
3    red  medium    metal              2             1                 0
4  green   small     wood              1             2                 2


In [5]:
#question 5


import pandas as pd
import numpy as np

# Create a sample dataset
data = {'Age': [25, 30, 22, 35, 28],
        'Income': [50000, 75000, 60000, 80000, 70000],
        'Education': [12, 16, 14, 18, 15]}

df = pd.DataFrame(data)

# Calculate the covariance matrix
covariance_matrix = np.cov(df, rowvar=False)

print("Covariance Matrix:")
print(covariance_matrix)


Covariance Matrix:
[[2.450e+01 5.000e+04 9.500e+00]
 [5.000e+04 1.450e+08 2.625e+04]
 [9.500e+00 2.625e+04 5.000e+00]]


In [ ]:
#question 