In [ ]:
#In Python, variables are dynamically typed, meaning that the interpreter automatically determines the type of a variable based on its value. However, if you want to check the type of a variable, you can use the type() function.

In [5]:
# Example variables
list_ = [1, 2, 3]
array_list = [4, 5, 6]

# Print the data types of the variables
print("Type of list_:", type(list_))
print("Type of array_list:", type(array_list))


Type of list_: <class 'list'>
Type of array_list: <class 'list'>


In [4]:
#question 2

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
#question 3

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))


Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [2]:
#question 4

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Find the shape of num_array
shape_of_num_array = num_array.shape
print("Shape of num_array:", shape_of_num_array)

# (ii) Find the size of num_array
size_of_num_array = num_array.size
print("Size of num_array:", size_of_num_array)


#arr.size and arr.shape are used respectively

Shape of num_array: (2, 3)
Size of num_array: 6


In [1]:
#question 5

import numpy as np

# Create a 3x3 matrix with zeros
zeros_matrix = np.zeros((3, 3))

# Print the resulting matrix
print("3x3 Matrix with Zeros:")
print(zeros_matrix)


3x3 Matrix with Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#question 6

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the resulting matrix
print("5x5 Identity Matrix:")
print(identity_matrix)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
